### ISSUE TITLE
Getting an error here

### ISSUE THREAD

**Issue by Dominator56** [dentych/EnchantGUI#25]
First, I don't even know if that's the correct place to post errors and stuff, but here is it:

```
[15:39:03] [Server thread/ERROR]: Could not pass event InventoryClickEvent to EnchantGUI v1.3.2
org.bukkit.event.EventException
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[craftbukkit-1.8.8.jar:git-Bukkit-930a59c]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[craftbukkit-1.8.8.jar:git-Bukkit-930a59c]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:501) [craftbukkit-1.8.8.jar:git-Bukkit-930a59c]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:486) [craftbukkit-1.8.8.jar:git-Bukkit-930a59c]
	at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:1564) [craftbukkit-1.8.8.jar:git-Bukkit-930a59c]
	at net.minecraft.server.v1_8_R3.PacketPlayInWindowClick.a(SourceFile:31) [craftbukkit-1.8.8.jar:git-Bukkit-930a59c]
	at net.minecraft.server.v1_8_R3.PacketPlayInWindowClick.a(SourceFile:9) [craftbukkit-1.8.8.jar:git-Bukkit-930a59c]
	at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [craftbukkit-1.8.8.jar:git-Bukkit-930a59c]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_71]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_71]
	at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [craftbukkit-1.8.8.jar:git-Bukkit-930a59c]
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:673) [craftbukkit-1.8.8.jar:git-Bukkit-930a59c]
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:335) [craftbukkit-1.8.8.jar:git-Bukkit-930a59c]
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:629) [craftbukkit-1.8.8.jar:git-Bukkit-930a59c]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:537) [craftbukkit-1.8.8.jar:git-Bukkit-930a59c]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_71]
Caused by: java.lang.NoSuchMethodError: org.bukkit.event.inventory.InventoryClickEvent.getClickedInventory()Lorg/bukkit/inventory/Inventory;
	at me.tychsen.enchantgui.Event.EventManager.handleInventoryClickEvent(EventManager.java:71) ~[?:?]
	at me.tychsen.enchantgui.Event.EventManager.onInventoryClickEvent(EventManager.java:42) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_71]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_71]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_71]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_71]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:300) ~[craftbukkit-1.8.8.jar:git-Bukkit-930a59c]
	... 15 more
 ```

I'm getting that when I click anything in the /eshop window.

Hope you can help me, I rebuilt the CraftBukkit jar today, to have the latest version if that's of any help.

**Comment by dentych** [comment]
Hello. Thank you for submitting this bug request.

The plugin is built for the Spigot API (an extension of Bukkit API). In the InventoryClickEvent there is a getClickedInventory() method that the plugin is utilizing. This method DOES NOT exist in the Bukkit API.

In order  to fix this, you should use the latest Spigot server instead of CraftBukkit. Spigot is basically the same, with some performance tweaks.

If you have any further questions please don't hesitate to contact me.

**Comment by Dominator56** [comment]
Ooooh alright, I didn't know what spigot was exactly but I will use it now. :)

**Comment by dentych** [comment]
Alright. It's a better version of Bukkit basically :) But good luck!
